ALTER TABLE transfers ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE transaction_requests ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE batches ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE tasks ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE variables ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE businesskeys ADD COLUMN ZEEBE_GENERATION BIGINT(20) NOT NULL DEFAULT 0;

CREATE INDEX idx_transfers_key_gen ON transfers (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
CREATE INDEX idx_transaction_requests_key_gen ON transaction_requests (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
CREATE INDEX idx_batches_key_gen ON batches (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
CREATE INDEX idx_tasks_key_gen ON tasks (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
CREATE INDEX idx_variables_key_gen ON variables (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
CREATE INDEX idx_businesskeys_key_gen ON businesskeys (WORKFLOW_INSTANCE_KEY, ZEEBE_GENERATION);
