trigger:
  branches:
    include:
      - main
      - develop
      - release/*
  paths:
    exclude:
      - README.md

pr:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md

pool:
  vmImage: "ubuntu-latest"

name: Oaf-PaymentHub_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - script: |
      VERSION_TAG=`git describe --abbrev=0 --tags`
      echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
      IMAGE_TAGS="${VERSION_TAG}"
      echo "##vso[task.setvariable variable=IMAGE_SEMANTIC_HASH]$IMAGE_TAGS"
      if [[ "$(Build.SourceBranch)" == "refs/heads/main" ]]; then IMAGE_TAGS="$IMAGE_TAGS,latest"; fi;
      echo Tags: $IMAGE_TAGS
      echo "##vso[task.setvariable variable=IMAGE_TAGS]$IMAGE_TAGS"
    displayName: Get git tag

  - script: |
      # Determine linting scope
      if [[ "${BUILD_REASON}" == "PullRequest" ]]; then
        echo "This is a PR build, scanning delta only"
        export VALIDATE_ALL_CODEBASE=false
        export GITHUB_SHA=$(git log -1 --pretty=%B | sed -e 's/^Merge //' -e 's/ into.*//')
      else
        echo "This is a regular build"
        export VALIDATE_ALL_CODEBASE=true
        export GITHUB_SHA=${BUILD_SOURCEVERSION}
      fi
      echo "VALIDATE_ALL_CODEBASE=${VALIDATE_ALL_CODEBASE}"
      echo "GITHUB_SHA=${GITHUB_SHA}"
      
      docker run -v "$(System.DefaultWorkingDirectory):/tmp/lint" \
        -e GITHUB_TOKEN \
        -e VALIDATE_ALL_CODEBASE \
        -e APPLY_FIXES=none \
        -e GITHUB_STATUS_REPORTER=true \
        -e GITHUB_COMMENT_REPORTER=true \
        -e CI=true \
        -e GITHUB_REF="$(Build.SourceBranch)" \
        -e GITHUB_REPOSITORY="$(Build.Repository.ID)" \
        -e GITHUB_TARGET_URL="$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(System.JobId)&t=$(System.TaskInstanceId)" \
        -e GITHUB_SHA \
        oxsecurity/megalinter-cupcake:latest
      displayName: MegaLinter analysis
      env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - task: Gradle@3
    displayName: Gradlew build
    inputs:
      gradleWrapperFile: "gradlew"
      tasks: "bootJar :test --info --build-cache"
      publishJUnitResults: true
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.11"
      # codeCoverageToolOption: 'JaCoCo'
      classFilesDirectories: build/classes/java/main/
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

  - task: Docker@2
    displayName: Login to Azure registry
    inputs:
      containerRegistry: azurecr-oaf
      command: "login"

  - task: Docker@2
    displayName: push image to registry
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    inputs:
      containerRegistry: "azurecr-oaf"
      repository: "oneacrefund/operations-app"
      command: "push"
      tags: "$(IMAGE_TAGS)"

  - task: PublishBuildArtifacts@1
    displayName: Publish configuration package
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: "operations-app"
      publishLocation: "Container"
